services:
  database:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: carlos
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
