export const cities = [
	{ value: 'CABA', label: 'Ciudad Autonoma de Buenos Aires' },
	{ value: 'Córdoba', label: 'Córdoba' },
	{ value: 'Rosario', label: 'Rosario' },
	{ value: 'Mendoza', label: 'Mendoza' },
	{ value: 'La Plata', label: 'La Plata' },
	{ value: 'San Miguel de Tucumán', label: 'San Miguel de Tucumán' },
	{ value: 'Mar del Plata', label: 'Mar del Plata' },
	{ value: 'Salta', label: 'Salta' },
	{ value: 'Santa Fe de la Vera Cruz', label: 'Santa Fe de la Vera Cruz' },
	{ value: 'San Juan', label: 'San Juan' },
	{ value: 'Resistencia', label: 'Resistencia' },
	{ value: 'Corrientes', label: 'Corrientes' },
	{ value: 'Posadas', label: 'Posadas' },
	{ value: 'San Salvador de Jujuy', label: 'San Salvador de Jujuy' },
	{ value: 'Bahía Blanca', label: 'Bahía Blanca' },
	{ value: 'Paraná', label: 'Paraná' },
	{ value: 'Neuquén', label: 'Neuquén' },
	{ value: 'Formosa', label: 'Formosa' },
	{ value: 'Santiago del Estero', label: 'Santiago del Estero' },
	{ value: 'Comodoro Rivadavia', label: 'Comodoro Rivadavia' },
	{ value: 'San Luis', label: 'San Luis' },
	{
		value: 'San Fernando del Valle de Catamarca',
		label: 'San Fernando del Valle de Catamarca'
	},
	{ value: 'La Rioja', label: 'La Rioja' },
	{ value: 'Río Gallegos', label: 'Río Gallegos' },
	{ value: 'Ushuaia', label: 'Ushuaia' },
	{ value: 'Viedma', label: 'Viedma' },
	{ value: 'Rawson', label: 'Rawson' },
	{ value: 'Santa Rosa', label: 'Santa Rosa' },
	{ value: 'Tandil', label: 'Tandil' },
	{ value: 'Concordia', label: 'Concordia' },
	{ value: 'Puerto Madryn', label: 'Puerto Madryn' },
	{ value: 'San Rafael', label: 'San Rafael' },
	{ value: 'Villa María', label: 'Villa María' },
	{ value: 'Río Cuarto', label: 'Río Cuarto' },
	{ value: 'San Carlos de Bariloche', label: 'San Carlos de Bariloche' },
	{ value: 'Olavarría', label: 'Olavarría' },
	{ value: 'Junín', label: 'Junín' },
	{ value: 'Pergamino', label: 'Pergamino' },
	{ value: 'Gualeguaychú', label: 'Gualeguaychú' },
	{ value: 'Necochea', label: 'Necochea' },
	{ value: 'Trelew', label: 'Trelew' },
	{ value: 'Rafaela', label: 'Rafaela' },
	{ value: 'Villa Mercedes', label: 'Villa Mercedes' },
	{ value: 'Orán', label: 'Orán' },
	{ value: 'Tartagal', label: 'Tartagal' },
	{ value: 'Presidencia Roque Sáenz Peña', label: 'Presidencia Roque Sáenz Peña' },
	{ value: 'Goya', label: 'Goya' },
	{ value: 'Oberá', label: 'Oberá' },
	{ value: 'Eldorado', label: 'Eldorado' },
	{ value: 'Zapala', label: 'Zapala' },
	{ value: 'General Roca', label: 'General Roca' },
	{ value: 'Cipolletti', label: 'Cipolletti' },
	{ value: 'Caleta Olivia', label: 'Caleta Olivia' },
	{ value: 'Pico Truncado', label: 'Pico Truncado' },
	{ value: 'Río Grande', label: 'Río Grande' },
	{ value: 'Villa Krause', label: 'Villa Krause' },
	{ value: 'Chimbas', label: 'Chimbas' },
	{ value: 'Rivadavia (San Juan)', label: 'Rivadavia (San Juan)' },
	{ value: 'Pocito', label: 'Pocito' },
	{ value: 'Luján de Cuyo', label: 'Luján de Cuyo' },
	{ value: 'Godoy Cruz', label: 'Godoy Cruz' },
	{ value: 'Las Heras (Mendoza)', label: 'Las Heras (Mendoza)' },
	{ value: 'Guaymallén', label: 'Guaymallén' },
	{ value: 'Maipú (Mendoza)', label: 'Maipú (Mendoza)' },
	{ value: 'San Martín (Mendoza)', label: 'San Martín (Mendoza)' },
	{ value: 'Yerba Buena', label: 'Yerba Buena' },
	{ value: 'Tafí Viejo', label: 'Tafí Viejo' },
	{ value: 'Banda del Río Salí', label: 'Banda del Río Salí' },
	{ value: 'Concepción (Tucumán)', label: 'Concepción (Tucumán)' },
	{ value: 'Alderetes', label: 'Alderetes' },
	{ value: 'Termas de Río Hondo', label: 'Termas de Río Hondo' },
	{ value: 'La Banda', label: 'La Banda' },
	{ value: 'Chilecito', label: 'Chilecito' },
	{ value: 'Villa Carlos Paz', label: 'Villa Carlos Paz' },
	{ value: 'Alta Gracia', label: 'Alta Gracia' },
	{ value: 'San Francisco (Córdoba)', label: 'San Francisco (Córdoba)' },
	{ value: 'Bell Ville', label: 'Bell Ville' },
	{ value: 'Jesús María', label: 'Jesús María' },
	{ value: 'Venado Tuerto', label: 'Venado Tuerto' },
	{ value: 'Reconquista', label: 'Reconquista' },
	{ value: 'Santo Tomé (Santa Fe)', label: 'Santo Tomé (Santa Fe)' },
	{ value: 'Esperanza', label: 'Esperanza' },
	{ value: 'Avellaneda (Buenos Aires)', label: 'Avellaneda (Buenos Aires)' },
	{ value: 'Lanús', label: 'Lanús' },
	{ value: 'Lomas de Zamora', label: 'Lomas de Zamora' },
	{ value: 'Quilmes', label: 'Quilmes' },
	{ value: 'Almirante Brown', label: 'Almirante Brown' },
	{ value: 'Merlo (Buenos Aires)', label: 'Merlo (Buenos Aires)' },
	{ value: 'Moreno', label: 'Moreno' },
	{ value: 'Florencio Varela', label: 'Florencio Varela' },
	{ value: 'Tigre', label: 'Tigre' },
	{ value: 'San Isidro', label: 'San Isidro' },
	{ value: 'Vicente López', label: 'Vicente López' },
	{ value: 'San Martín (Buenos Aires)', label: 'San Martín (Buenos Aires)' },
	{ value: 'Tres de Febrero', label: 'Tres de Febrero' },
	{ value: 'Morón', label: 'Morón' },
	{ value: 'Esteban Echeverría', label: 'Esteban Echeverría' },
	{ value: 'Ezeiza', label: 'Ezeiza' },
	{ value: 'Berazategui', label: 'Berazategui' },
	{ value: 'Ituzaingó (Buenos Aires)', label: 'Ituzaingó (Buenos Aires)' },
	{ value: 'Hurlingham', label: 'Hurlingham' },
	{ value: 'San Fernando (Buenos Aires)', label: 'San Fernando (Buenos Aires)' },
	{ value: 'Malvinas Argentinas', label: 'Malvinas Argentinas' },
	{ value: 'José C. Paz', label: 'José C. Paz' },
	{ value: 'Pilar', label: 'Pilar' },
	{ value: 'Escobar', label: 'Escobar' },
	{ value: 'Campana', label: 'Campana' },
	{ value: 'Zárate', label: 'Zárate' }
];
